title: Hello, I'm Sandeep Kumar 
logo: "/images/image.png?raw=true" 
description: >
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/sandeep-kumar1907/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-RV1DPFDYWY # your Google Analytics tracking ID here
